spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meltingpot
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 80MB
      max-request-size: 80MB
